//User action types

export const LOGGING_USER_STARTED = "LOGGING_USER_STARTED";
export const LOGGING_USER_RESOLVED = "LOGGING_USER_RESOLVED";
export const LOGGING_USER_REJECTED = "LOGGING_USER_REJECTED";
export const STOP_ASYNC_LOGGING_USER = "STOP_ASYNC_LOGGING_USER";
export const LOG_OUT = "LOG_OUT";

// Dashboard action types
export const FETCHING_ACTIVE_DEVICE_STARTED = "FETCHING_ACTIVE_DEVICE_STARTED";
export const FETCHING_ACTIVE_DEVICE_RESOLVED =
  "FETCHING_ACTIVE_DEVICE_RESOLVED";
export const FETCHING_ACTIVE_DEVICE_REJECTED =
  "FETCHING_ACTIVE_DEVICE_REJECTED";
export const STOP_ASYNC_FETCHING_DEVICE = "STOP_ASYNC_FETCHING_DEVICE";

export const FETCHING_ACTIVE_INFUSION_STARTED =
  "FETCHING_ACTIVE_INFUSION_STARTED";
export const FETCHING_ACTIVE_INFUSION_RESOLVED =
  "FETCHING_ACTIVE_INFUSION_RESOLVED";
export const FETCHING_ACTIVE_INFUSION_REJECTED =
  "FETCHING_ACTIVE_INFUSION_REJECTED";
export const STOP_ASYNC_FETCHING_INFUSION = "STOP_ASYNC_FETCHING_INFUSION";

export const FETCHING_ACTIVE_NURSES_STARTED = "FETCHING_ACTIVE_NURSES_STARTED";
export const FETCHING_ACTIVE_NURSES_RESOLVED =
  "FETCHING_ACTIVE_NURSES_RESOLVED";
export const FETCHING_ACTIVE_NURSES_REJECTED =
  "FETCHING_ACTIVE_NURSES_REJECTED";
export const STOP_ASYNC_FETCHING_NURSES = "STOP_ASYNC_FETCHING_NURSES";
