//User action types

export const LOGGING_USER_STARTED = "LOGGING_USER_STARTED";
export const LOGGING_USER_RESOLVED = "LOGGING_USER_RESOLVED";
export const LOGGING_USER_REJECTED = "LOGGING_USER_REJECTED";
export const STOP_ASYNC_LOGGING_USER = "STOP_ASYNC_LOGGING_USER";
export const LOG_OUT = "LOG_OUT";

// Dashboard action types
export const FETCHING_DASHBOARDS_STARTED = "FETCHING_DASHBOARDS_STARTED";
export const FETCHING_DASHBOARDS_RESOLVED = "FETCHING_DASHBOARDS_RESOLVED";
export const FETCHING_DASHBOARDS_REJECTED = "FETCHING_DASHBOARDS_REJECTED";
export const STOP_ASYNC_FETCHING_DASHBOARD = "STOP_ASYNC_FETCHING_DASHBOARDS";

export const UPDATING_DASHBOARD_STARTED = "UPDATING_DASHBOARD_STARTED";
export const UPDATING_DASHBOARD_RESOLVED = "UPDATING_DASBOARD_RESOLVED";
export const UPDATING_DASHBOARD_REJECTED = "UPDATING_DASHBOARD_REJECTED";
export const SET_DASHBOARD_TO_UPDATE = "SET_DASHBOARD_TO_UPDATE";
export const STOP_ASYNC_UPDATING_DASHBOARD = "STOP_ASYNC_UPDATING_DASHBOARD";
