//User action types

export const LOGGING_USER_STARTED = "LOGGING_USER_STARTED";
export const LOGGING_USER_RESOLVED = "LOGGING_USER_RESOLVED";
export const LOGGING_USER_REJECTED = "LOGGING_USER_REJECTED";
export const STOP_ASYNC_LOGGING_USER = "STOP_ASYNC_LOGGING_USER";
export const LOG_OUT = "LOG_OUT";
